version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_username
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./2_data.sql:/docker-entrypoint-initdb.d/2_data.sql
    restart: unless-stopped
    cpuset: "0,1"

volumes:
  postgres-data:
